import type { Metadata } from 'next';
import './globals.css';
// import Navbar from '@/components/blocks/navbar';
import NavBar from '@/components/layout/navbar';
export const metadata: Metadata = {
  title: 'All Things Linux',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="">
          <div className="container mx-auto px-4 py-4">
              <NavBar />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}

